spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: "jdbc:h2:mem:legal_prose_repository"
    driverClassName: org.h2.Driver
    username: 5gzorro_admin
    password: 5gzorro

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

server:
  port: 8081

integrations:
  governanceManager:
    apiBaseUrl: ${GOVERNANCE_BASE_URL:http://localhost:8080/api/v1}