server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /legal-prose-repository

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true

spring:
  profiles:
    active:
      - staging
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB_NAME:postgres}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_DB_USER:postgres}
    password: ${POSTGRES_DB_PASSWORD:postgres}

integrations:
  identity-permissions:
    myAgentBaseUrl: ${IDENTITY_BASE_URL:http://172.28.3.153:6200}
    did: ${IDENTITY_DID:OD1ndI3xw0Pi6Sl4rgoa6F}
  governanceManager:
    apiBaseUrl: ${GOVERNANCE_BASE_URL:http://localhost:8080/api/v1}

callbacks:
  updateTemplateIdentity: ${UPDATE_TEMPLATE_IDENTITY_CALLBACK_URL:http://localhost:8080/legal-prose-repository/api/v1/legal-prose-templates/%s/identity}