spring:
  profiles:
    active:
      - dev
  jpa:
    #    show-sql: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5222/legal_prose_repository"
    driverClassName: org.postgresql.Driver
    username: 5gzorro_admin
    password: 5gzorro
    initialization-mode: never

integrations:
  identity-permissions:
    myAgentBaseUrl: ${IDENTITY_BASE_URL:http://localhost:6200}
  governanceManager:
    apiBaseUrl: ${GOVERNANCE_BASE_URL:http://localhost:8080/api/v1}

callbacks:
  updateTemplateIdentity: ${UPDATE_TEMPLATE_IDENTITY_CALLBACK_URL:http://localhost:8081/api/v1/legal-prose-templates/%s/identity}