spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: "jdbc:h2:mem:legal_prose_repository"
    driverClassName: org.h2.Driver
    username: 5gzorro_admin
    password: 5gzorro

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

server:
  port: 8081

logging:
  level:
    eu._5gzorro.legalproserepository.httpClient: DEBUG

integrations:
  identity-permissions:
    apiBaseUrl: ${IDENTITY_BASE_URL:http://localhost:6200}
  governanceManager:
    apiBaseUrl: ${GOVERNANCE_BASE_URL:http://localhost:8080/api/v1}

callbacks:
  updateTemplateIdentity: ${UPDATE_TEMPLATE_IDENTITY_CALLBACK_URL:http://localhost:8081/api/v1/legal-prose-templates/%s/identity}