spring:
  profiles:
    active:
      - dev
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${postgres.db.host:localhost}:${postgres.db.port:5432}/${postgres.db.name:legalproserepository}
    driverClassName: org.postgresql.Driver
    username: ${postgres.db.user:5gzorro_admin}
    password: ${postgres.db.password:5gzorro}

integrations:
  identity-permissions:
    apiBaseUrl: ${IDENTITY_BASE_URL:http://localhost:6200}
  governanceManager:
    apiBaseUrl: ${GOVERNANCE_BASE_URL:http://localhost:8080/api/v1}

callbacks:
  updateTemplateIdentity: ${UPDATE_TEMPLATE_IDENTITY_CALLBACK_URL:http://localhost:8081/api/v1/legal-prose-templates/%s/identity}