spring:
  profiles:
    active:
      - dev
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB_NAME:governance}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_DB_USER:5gzorro_admin}
    password: ${POSTGRES_DB_PASSWORD:5gzorro}

integrations:
  identity-permissions:
    apiBaseUrl: ${IDENTITY_BASE_URL:http://localhost:6200}
  governanceManager:
    apiBaseUrl: ${GOVERNANCE_BASE_URL:http://localhost:8080/api/v1}

callbacks:
  updateTemplateIdentity: ${UPDATE_TEMPLATE_IDENTITY_CALLBACK_URL:http://localhost:8081/api/v1/legal-prose-templates/%s/identity}