on: 
  workflow_dispatch:
name: deploy-to-kubernetes
jobs:
  deploy-operatora-ns:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir ~/.kube/ && echo "${{ secrets.KUBECONFIG_FILE}}" | base64 -d > ~/.kube/config
    - run: echo "${{ secrets.CA_CRT }}" | base64 -d > ca.crt
    - run: echo "${{ secrets.TLS_KEY }}" | base64 -d > ta.key
    - uses: azure/setup-helm@v1
      with:
        version: '3.1.2'
      id: install
    - name: Install Open VPN
      run: sudo apt-get update && sudo apt-get install openvpn openvpn-systemd-resolved -y
    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v1"
      with:
        config_file: .github/vpn/config.ovpn
        username: ${{ secrets.OVPN_USERNAME }}
        password: ${{ secrets.OVPN_PASSWORD }}
    - name: Deploy to K8s cluster
      run: |
          helm upgrade legal-prose-api ./helm/charts/legal-prose-repository/ \
            --namespace operatora-ns \
            --repo ./helm/charts/legal-prose-repository/ \
            --values ./helm/charts/legal-prose-repository/values.yaml \
            --set postgres.username=${{ secrets.OPERATORA_POSTGRES_USERNAME }} \
            --set postgres.password=${{ secrets.OPERATORA_POSTGRES_PASSWORD }}